export enum ErrorCode {
    succ = 0,
    fail = 1,
    noMoreData = 2,
    unknownCommand = 3,
    netError = 4,
    exist = 5,
    notExist = 6,
    exception = 7,
    notChange = 8,
    invalidState = 9,
    timeout = 10,
    md5NotMatch = 11,
    notSupport = 12,
    invalidParam = 13,
    notFound = 14,
    waiting = 15,
    break = 16,
}