[config]
version = "2.12"
reportCrash = false
removeLog = false
heartbeatIntervalTime = 60000

[config.agentServer]
host="192.168.100.205"
port = 11080

[config.updateServer]
host="192.168.100.205"
port = 9012

[config.reportServer]
host="192.168.100.205"
port = 11000

[config.fileUploadServer]
host="192.168.100.205"
port = 11000

