[config]
DRIVER_TYPE = "Simulator"

[config.real_machine]

[config.real_machine.zone1]
[config.real_machine.zone1.ood]
peer_name= "zone1_ood"
zone_tag= "zone1"
stack_type="ood"
bdt_port= 30001
http_port= 31000
ws_port=31001
ood_daemon_status_port = 32001

[config.real_machine.zone1.device1]
peer_name= "zone1_device1" 
zone_tag= "zone1" 
stack_type= "runtime" 
bdt_port= 30002 
http_port= 31002 
ws_port= 31003 

[config.real_machine.zone1.device2]
peer_name = "zone1_device2" 
zone_tag = "zone1" 
stack_type = "runtime" 
bdt_port=30003 
http_port=31004 
ws_port= 31005 

[config.real_machine.zone1.zone1_standby_ood]
peer_name = "zone1_standby_ood" 
zone_tag = "zone1" 
stack_type = "ood" 
bdt_port=30004 
http_port=31006 
ws_port= 31007 
ood_daemon_status_port = 32002 


[config.real_machine.zone2]
[config.real_machine.zone2.ood]
peer_name= "zone2_ood" 
zone_tag= "zone2" 
stack_type= "ood" 
bdt_port= 30010 
http_port= 31010 
ws_port= 31011 
ood_daemon_status_port = 32003 


[config.real_machine.zone2.device1]
peer_name= "zone2_device1" 
zone_tag= "zone2" 
stack_type= "runtime" 
bdt_port= 30011 
http_port= 31012 
ws_port= 31013 

[config.real_machine.zone2.device2]
peer_name = "zone2_device2" 
zone_tag = "zone2" 
stack_type = "runtime" 
bdt_port=30012 
http_port=31014 
ws_port= 31015 


    

[config.simulator.zone1]

[config.simulator.zone1.ood]
peer_name= "zone1_ood" 
zone_tag= "zone1" 
stack_type= "ood" 
bdt_port= 20001 
http_port= 21000 
ws_port= 21001 

[config.simulator.zone1.device1]
peer_name= "zone1_device1" 
zone_tag= "zone1" 
stack_type= "runtime" 
bdt_port= 20002 
http_port= 21002 
ws_port= 21003 

[config.simulator.zone1.device2]
peer_name= "zone1_device2" 
zone_tag= "zone1" 
stack_type= "runtime" 
bdt_port= 20003 
http_port= 21004 
ws_port= 21005 

[config.simulator.zone1.standby_ood]
peer_name= "zone1_standby_ood" 
zone_tag= "zone1" 
stack_type= "ood" 
bdt_port= 20004 
http_port= 21006 
ws_port= 21007

[config.simulator.zone2]

[config.simulator.zone2.ood]
peer_name= "zone2_ood" 
zone_tag= "zone2" 
stack_type= "ood" 
bdt_port= 20010 
http_port= 21010 
ws_port= 21011 

[config.simulator.zone2.device1]
peer_name= "zone2_device1" 
zone_tag= "zone2" 
stack_type= "runtime" 
bdt_port= 20011 
http_port= 21012 
ws_port= 21013 

[config.simulator.zone2.device2]
peer_name= "zone2_device2" 
zone_tag= "zone2" 
stack_type= "runtime" 
bdt_port= 20012 
http_port= 21014 
ws_port= 21015 
