import {testSuiteJson} from '../../common' 
export const datas :testSuiteJson = {
system:"cyfs-stack",
module : "NON_get_object",
testcaseList : [
{id:"get_object_Param_0021",name:"#get_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"get_object_Param_0020",name:"#get_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"get_object_Param_0013",name:"#get_object handler参数测试 routineType 设置为自定义hnadler GetObjectHandlerPass 类型"},
{id:"get_object_Param_0012",name:"#get_object handler参数测试 routineType 设置为自定义hnadler GetObjectHandlerDrop 类型"},
{id:"get_object_Param_0011",name:"#get_object handler参数测试 routineType 设置为自定义hnadler GetObjectHandlerReject类型"},
{id:"get_object_Param_0010",name:"#get_object handler参数测试 routineType 设置为自定义hnadler GetObjectHandlerDefault类型"},
{id:"get_object_Param_0009",name:"#get_object handler参数测试 index index 数值小的handler生效"},
{id:"get_object_Param_0008",name:"#get_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Reject"},
{id:"get_object_Param_0008_01",name:"#get_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Default"},
{id:"get_object_Param_0007",name:"#get_object handler参数测试 id 设置相同id Default覆盖Reject操作"},
{id:"get_object_Param_0006",name:"#get_object handler参数测试 id 设置相同id Reject覆盖Default操作"},
{id:"get_object_Param_0005",name:"#get_object handler参数测试 default_action 设置为Pass"},
{id:"get_object_Param_0004",name:"#get_object handler参数测试 default_action 设置为Response"},
{id:"get_object_Param_0003",name:"#get_object handler参数测试 default_action 设置为Drop"},
{id:"get_object_Param_0002",name:"#get_object handler参数测试 default_action 设置为Reject"},
{id:"get_object_Param_0001",name:"#get_object handler参数测试 default_action 设置为Default"},
{id:"get_object_router_0050",name:"#get_object-Router target 为跨zone device2 设置device2 handler PostNOC 为reject"},
{id:"get_object_router_0049",name:"#get_object-Router target 为跨zone device2 设置device2 handler PreNOC 为reject"},
{id:"get_object_router_0048",name:"#get_object-Router target 为跨zone device2 设置device2 handler PostRouter 为reject"},
{id:"get_object_router_0047",name:"#get_object-Router target 为跨zone device2 设置device2 handler PreRouter 为reject"},
{id:"get_object_router_0046",name:"#get_object-Router target 为跨zone device2 设置device2 ACL in 为reject"},
{id:"get_object_router_0029_b",name:"#get_object-Router target 为跨zone device2 设置device1 ACL-out 为 reject"},
{id:"get_object_router_0028_d",name:"#get_object-Router target 为跨zone device2 设置device1 PostForward 为 reject"},
{id:"get_object_router_0028_c",name:"#get_object-Router target 为跨zone device2 设置device1 PreForward 为 reject"},
{id:"get_object_router_0027_b",name:"#get_object-Router target 为跨zone device2 设置device1 PostNOC为 reject"},
{id:"get_object_router_0026_b",name:"#get_object-Router target 为跨zone device2 设置device1 PreNOC为 reject"},
{id:"get_object_router_0025X",name:"#get_object-Router target 为跨zone device2 设置device1 PostRouter为 reject"},
{id:"get_object_router_0024_b",name:"#get_object-Router target 为跨zone device2 设置device1 PreRouter为 reject"},
{id:"get_object_router_0023X",name:"#get_object-Router target 为跨zone device2 设置handler-ACL 全部为default"},
{id:"get_object_router_0022_b",name:"#get_object-Router target 为跨zone device2 未设置handler-ACL"},
{id:"get_object_router_0042_a",name:"#get_object-Router target 为跨zone ood 设置 ood2 handler PostNOC 为reject"},
{id:"get_object_router_0041_a",name:"#get_object-Router target 为跨zone ood 设置ood2 handler PreNOC 为reject"},
{id:"get_object_router_0040_a",name:"#get_object-Router target 为跨zone ood 设置ood2 handler PostRouter 为reject"},
{id:"get_object_router_0039_a",name:"#get_object-Router target 为跨zone ood 设置ood2 handler PreRouter 为reject"},
{id:"get_object_router_0038_a",name:"#get_object-Router target 为跨zone ood 设置ood2 ACL-in 为reject"},
{id:"get_object_router_0029_a",name:"#get_object-Router target 为跨zone ood 设置device1 ACL-out 为 reject"},
{id:"get_object_router_0028_b",name:"#get_object-Router target 为跨zone ood 设置device1 PostForward 为 reject"},
{id:"get_object_router_0028_a",name:"#get_object-Router target 为跨zone ood 设置device1 PreForward 为 reject"},
{id:"get_object_router_0027_a",name:"#get_object-Router target 为跨zone ood 设置device1 PostNOC为 reject"},
{id:"get_object_router_0026_a",name:"#get_object-Router target 为跨zone ood 设置device1 PreNOC为 reject"},
{id:"get_object_router_0025_a",name:"#get_object-Router target 为跨zone ood 设置device1 PostRouter为 reject"},
{id:"get_object_router_0024_a",name:"#get_object-Router target 为跨zone ood 设置device1 PreRouter为 reject"},
{id:"get_object_router_0023_a",name:"#get_object-Router target 为跨zone ood 设置handler-ACL 全部为default"},
{id:"get_object_router_0022_a",name:"#get_object-Router target 为跨zone ood 未设置handler-ACL"},
{id:"get_object_router_0042",name:"#get_object-Router target 为同zone device2 设置device2 handler PostNOC 为reject"},
{id:"get_object_router_0041",name:"#get_object-Router target 为同zone device2 设置device2 handler PreNOC 为reject"},
{id:"get_object_router_0040",name:"#get_object-Router target 为同zone device2 设置device2 handler PostRouter 为reject"},
{id:"get_object_router_0039",name:"#get_object-Router target 为同zone device2 设置device2 handler PreRouter 为reject"},
{id:"get_object_router_0038",name:"#get_object-Router target 为同zone device2 设置device2 ACL-in 为reject"},
{id:"get_object_router_0029",name:"#get_object-Router target 为同zone device2 设置device1 ACL-out 为 reject"},
{id:"get_object_router_0028_02",name:"#get_object-Router target 为同zone device2 设置device1 PostForward 为 reject"},
{id:"get_object_router_0028",name:"#get_object-Router target 为同zone device2 设置device1 PreForward 为 reject"},
{id:"get_object_router_0027",name:"#get_object-Router target 为同zone device2 设置device1 PostNOC为 reject"},
{id:"get_object_router_0026",name:"#get_object-Router target 为同zone device2 设置device1 PreNOC为 reject"},
{id:"get_object_router_0025",name:"#get_object-Router target 为同zone device2 设置device1 PostRouter为 reject"},
{id:"get_object_router_0024",name:"#get_object-Router target 为同zone device2 设置device1 PreRouter为 reject"},
{id:"get_object_router_0023",name:"#get_object-Router target 为同zone device2 设置handler-ACL 全部为default"},
{id:"get_object_router_0022",name:"#get_object-Router target 为同zone device2 未设置handler-ACL"},
{id:"get_object_router_0021",name:"#get_object-Router target 为同zone OOD  OOD1 设置 PostNOC reject"},
{id:"get_object_router_0020",name:"#get_object-Router target 为同zone OOD  OOD1 设置 PreNOC reject"},
{id:"get_object_router_0019",name:"#get_object-Router target 为同zone OOD  OOD1 设置 PostRouter reject"},
{id:"get_object_router_0018",name:"#get_object-Router target 为同zone OOD  OOD1 设置 PreRouter reject"},
{id:"get_object_router_0017",name:"#get_object-Router target 为同zone OOD  OOD1 设置 ACL-IN reject"},
{id:"get_object_router_0016",name:"#get_object-Router target 为同zone OOD  source设备 设置 PostForward reject"},
{id:"get_object_router_0015",name:"#get_object-Router target 为同zone OOD  source设备 设置 PreForward reject"},
{id:"get_object_router_0014",name:"#get_object-Router target 为同zone OOD  source设备 设置 PostNOC reject"},
{id:"get_object_router_0013",name:"#get_object-Router target 为同zone OOD  source设备 设置 PreNOC reject"},
{id:"get_object_router_0012",name:"#get_object-Router target 为同zone OOD  source设备 设置 PostRouter reject"},
{id:"get_object_router_0011",name:"#get_object-Router target 为同zone OOD  source设备 设置 PreRouter reject"},
{id:"get_object_router_0010",name:"#get_object-Router target 为同zone OOD  source设备 设置 OUT ACL reject"},
{id:"get_object_router_0009",name:"#get_object-Router target 为同zone OOD  设置handler-ACL 为default"},
{id:"get_object_router_0008",name:"#get_object-Router target 为同zone OOD  未设置handler-ACL"},
{id:"get_object_router_0007",name:"#get_object-Router target 为本地设备  设置handler PostRouter reject"},
{id:"get_object_router_0006",name:"#get_object-Router target 为本地设备  设置handler PostRouter reject"},
{id:"get_object_router_0005",name:"#get_object-Router target 为本地设备  设置handler PostNOC reject"},
{id:"get_object_router_0004",name:"#get_object-Router target 为本地设备  设置handler PreNOC reject"},
{id:"get_object_router_0003",name:"#get_object-Router target 为本地设备  设置handler PreRouter reject"},
{id:"get_object_router_0002",name:"#get_object-Router target 为本地设备  设置handler-ACL为默认"},
{id:"get_object_router_0001",name:"#get_object-Router target 为本地设备  未设置handler-ACL"},
{id:"get_object_non_0017",name:"#get_object-NON target 为同zone device2  设置target设备 handler PostNOC reject"},
{id:"get_object_non_0016",name:"#get_object-NON target 为同zone device2  设置target设备 handler PreNOC reject"},
{id:"get_object_non_0015_new",name:"#get_object-NON target 为同zone device2  设置source设备 handler PostForward reject"},
{id:"get_object_non_0015",name:"#get_object-NON target 为同zone device2  设置source设备 handler PreForward reject"},
{id:"get_object_non_0014",name:"#get_object-NON target 为同zone device2  设置handler-acl 为默认 default"},
{id:"get_object_non_0013",name:"#get_object-NON target 为同zone device2  未设置handler-acl 流程 "},
{id:"get_object_non_0012",name:"#get_object-NON target 为同zone OOD  设置handler OOD PostNOC reject"},
{id:"get_object_non_0011",name:"#get_object-NON target 为同zone OOD  设置handler OOD PreNOC reject"},
{id:"get_object_non_0010",name:"#get_object-NON target 为同zone OOD  设置handler OOD ACL reject "},
{id:"get_object_non_0009",name:"#get_object-NON target 为同zone OOD  设置handler device1 ACL reject "},
{id:"get_object_non_0008",name:"#get_object-NON target 为同zone OOD  设置handler device1 PostForward reject "},
{id:"get_object_non_0007",name:"#get_object-NON target 为同zone OOD  设置handler device1 PreForward reject "},
{id:"get_object_non_0006",name:"#get_object-NON target 为同zone OOD  设置handlerACL default-正常流程"},
{id:"get_object_non_0005",name:"#get_object-NON target 为同zone OOD  无handlerACL流程-正常流程"},
{id:"get_object_non_0004",name:"#get_object-NON target 本地设备 设置所有handler PostNOC reject"},
{id:"get_object_non_0003",name:"#get_object-NON target 本地设备 设置所有handler PreNOC reject"},
{id:"get_object_non_0002",name:"#get_object-NON target 本地设备 设置所有handlerACL default"},
{id:"get_object_non_0001",name:"#get_object-NON target 本地设备 无handlerACL流程-正常流程"},
{id:"get_object_noc_0004",name:"#get_object-NOC流程-设置 handler PostNOC reject"},
{id:"get_object_noc_0003",name:"#get_object-NOC流程-设置 handler PreNOC reject"},
{id:"get_object_noc_0002",name:"#get_object-NOC流程-设置所有handlerACL default"},
{id:"get_object_noc_0001",name:"#get_object-NOC 无handlerACL流程-正常流程"},
]
}