import {testSuiteJson} from '../../common' 
export const datas :testSuiteJson = {
system:"cyfs-stack",
module : "NDN_File",
testcaseList : [
{id:"NDN_file_fileSize_007",name:"#file 通过Router 调用 start_task 下载2Gb正常流程"},
{id:"NDN_file_fileSize_006",name:"#file 通过Router 调用 start_task 下载1Gb正常流程"},
{id:"NDN_file_fileSize_005",name:"#file 通过Router 调用 start_task 下载100Mb正常流程"},
{id:"NDN_file_fileSize_004",name:"#file 通过Router 调用 start_task 下载1Mb正常流程"},
{id:"NDN_file_fileSize_003",name:"#file 通过Router 调用 start_task 下载1Kb正常流程"},
{id:"NDN_file_fileSize_002",name:"#file 通过Router 调用 start_task 下载1byte正常流程"},
{id:"NDN_file_fileSize_001",name:"#file 通过Router 调用 start_task 下载空文件正常流程"},
{id:"NDN_file_chunkSize_008",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为64Mb 正常流程"},
{id:"NDN_file_chunkSize_007",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为32Mb 正常流程"},
{id:"NDN_file_chunkSize_006",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为16Mb 正常流程"},
{id:"NDN_file_chunkSize_005",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为8Mb 正常流程"},
{id:"NDN_file_chunkSize_004",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为4Mb 正常流程"},
{id:"NDN_file_chunkSize_003",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为2Mb 正常流程"},
{id:"NDN_file_chunkSize_002",name:"#file 通过Router 调用 start_task 下载100M文件chunk大小为1Mb 正常流程"},
{id:"NDN_file_chunkSize_001",name:"#file 通过Router 调用 start_task 下载1M文件chunk大小为1kb 正常流程"},
{id:"NDN_file_zone_router_008",name:"#file 通过Router 调用 start_task 下载 发送端为ood 接收端为跨zone ood 正常流程"},
{id:"NDN_file_zone_router_007",name:"#file 通过Router 调用 start_task 下载 发送端为ood 接收端为跨zone device1 正常流程"},
{id:"NDN_file_zone_router_006",name:"#file 通过Router 调用 start_task 下载 发送端为ood 接收端为同zone device1 正常流程"},
{id:"NDN_file_zone_router_005",name:"#file 通过Router 调用 start_task 下载 发送端为device1 接收端为跨zone device2 正常流程"},
{id:"NDN_file_zone_router_004",name:"#file 通过Router 调用 start_task 下载 发送端为device1 接收端为跨zone ood 正常流程"},
{id:"NDN_file_zone_router_003",name:"#file 通过Router 调用 start_task 下载 发送端为device1 接收端为同zone device2 正常流程"},
{id:"NDN_file_zone_router_002",name:"#file 通过Router 调用 start_task 下载 发送端为device1 接收端为同zone ood 正常流程"},
{id:"NDN_file_zone_router_001",name:"#file 通过Router 调用 start_task 下载 发送端为device1 接收端为本地 正常流程"},
{id:"NDN_file_zone_ndn_004",name:"#file 通过NDN 调用 start_task 下载 发送端为ood 接收端为同zone device1 正常流程"},
{id:"NDN_file_zone_ndn_003",name:"#file 通过NDN 调用 start_task 下载 发送端为device1 接收端为同zone device2 正常流程"},
{id:"NDN_file_zone_ndn_002",name:"#file 通过NDN 调用 start_task 下载 发送端为device1 接收端为同zone ood 正常流程"},
{id:"NDN_file_zone_ndn_001",name:"#file 通过NDN 调用 start_task 下载 发送端为device1 接收端为本地 正常流程"},
{id:"NDN_file_zone_ndc_001",name:"#file 下载通过NDC 调用 start_task 正常流程"},
{id:"NDN_file_second_002",name:"#file 通过Router 调用 start_task 下载100Mb正常流程"},
{id:"NDN_file_second_001",name:"#file 通过Router 调用 start_task 下载1Mb正常流程"},
]
}