import {testSuiteJson} from '../../common' 
export const datas :testSuiteJson = {
system:"cyfs-stack",
module : "NON_crypto",
testcaseList : [
{id:"verify_object_Param_0021",name:"#verify_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"verify_object_Param_0020",name:"#verify_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"verify_object_Param_0010",name:"#verify_object handler参数测试 routineType 设置为自定义hnadler CryptoHandlerDefault类型"},
{id:"verify_object_Param_0009",name:"#verify_object handler参数测试 index index 数值小的handler生效"},
{id:"verify_object_Param_0008",name:"#verify_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Reject"},
{id:"verify_object_Param_0008_01",name:"#verify_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Default"},
{id:"verify_object_Param_0007",name:"#verify_object handler参数测试 id 设置相同id Default覆盖Reject操作"},
{id:"verify_object_Param_0006",name:"#verify_object handler参数测试 id 设置相同id Reject覆盖Default操作"},
{id:"verify_object_Param_0005",name:"#verify_object handler参数测试 default_action 设置为Pass"},
{id:"verify_object_Param_0004",name:"#verify_object handler参数测试 default_action 设置为Response"},
{id:"verify_object_Param_0003",name:"#verify_object handler参数测试 default_action 设置为Drop"},
{id:"verify_object_Param_0002",name:"#verify_object handler参数测试 default_action 设置为Reject"},
{id:"verify_object_Param_0001",name:"#verify_object handler参数测试 default_action 设置为Default"},
{id:"sign_object_Param_0021",name:"#sign_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"sign_object_Param_0020",name:"#sign_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"sign_object_Param_0019",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseUpdated 类型"},
{id:"sign_object_Param_0018",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseMerged 类型"},
{id:"sign_object_Param_0017",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseAlreadyExists 类型"},
{id:"sign_object_Param_0016",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseAcceptWithSign 类型"},
{id:"sign_object_Param_0015",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseAccept 类型"},
{id:"sign_object_Param_0014",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponse 类型"},
{id:"sign_object_Param_0013",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerPass 类型"},
{id:"sign_object_Param_0012",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerDrop 类型"},
{id:"sign_object_Param_0011",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerReject类型"},
{id:"sign_object_Param_0010",name:"#sign_object handler参数测试 routineType 设置为自定义hnadler CryptoHandlerDefault类型"},
{id:"sign_object_Param_0009",name:"#sign_object handler参数测试 index index 数值小的handler生效"},
{id:"sign_object_Param_0008",name:"#sign_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Reject"},
{id:"sign_object_Param_0008_01",name:"#sign_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Default"},
{id:"sign_object_Param_0007",name:"#sign_object handler参数测试 id 设置相同id Default覆盖Reject操作"},
{id:"sign_object_Param_0006",name:"#sign_object handler参数测试 id 设置相同id Reject覆盖Default操作"},
{id:"sign_object_Param_0005",name:"#sign_object handler参数测试 default_action 设置为Pass"},
{id:"sign_object_Param_0004",name:"#sign_object handler参数测试 default_action 设置为Response"},
{id:"sign_object_Param_0003",name:"#sign_object handler参数测试 default_action 设置为Drop"},
{id:"sign_object_Param_0002",name:"#sign_object handler参数测试 default_action 设置为Reject"},
{id:"sign_object_Param_0001",name:"#sign_object handler参数测试 default_action 设置为Default"},
{id:"sign_object_0001",name:"#crypto sign_object-NOC流程-设置所有handlerACL default"},
]
}