import {testSuiteJson} from '../../common' 
export const datas :testSuiteJson = {
system:"cyfs-stack",
module : "NDN_chunk",
testcaseList : [
{id:"NDN_chunk_second_003",name:"#chunk 大小设置为 4 Mb"},
{id:"NDN_chunk_second_002",name:"#chunk 大小设置为 16 Mb"},
{id:"NDN_chunk_second_001",name:"#chunk 大小设置为 8 Mb"},
{id:"NDN_chunk_zone_optType_004",name:"#chunk 通过Router 调用put_data 非本地传输 接口暂时不支持"},
{id:"NDN_chunk_zone_optType_003",name:"#chunk 通过Router 调用put_data 本地传输  正常流程"},
{id:"NDN_chunk_zone_optType_002",name:"#chunk 通过Router 调用get_data 同Zone 发送端为 device1 接收端为 OOD 正常流程"},
{id:"NDN_chunk_zone_optType_001",name:"#chunk 通过Router 调用get_data 同Zone 本地传输  正常流程"},
{id:"NDN_chunk_handler_001",name:"#Router#chunk 通过Router 调用get_data 跨Zone 发送端为 zone1_device1 接收端为 zone2_ood 正常流程"},
{id:"NDN_chunk_zone_size_010",name:"#chunk 大小设置为 128 Mb"},
{id:"NDN_chunk_zone_size_009",name:"#chunk 大小设置为 64 Mb"},
{id:"NDN_chunk_zone_size_008",name:"#chunk 大小设置为 32 Mb"},
{id:"NDN_chunk_zone_size_007",name:"#chunk 大小设置为 16 Mb"},
{id:"NDN_chunk_zone_size_006",name:"#chunk 大小设置为 8 Mb"},
{id:"NDN_chunk_zone_size_005",name:"#chunk 大小设置为 4 Mb"},
{id:"NDN_chunk_zone_size_004",name:"#chunk 大小设置为 1 Mb"},
{id:"NDN_chunk_zone_size_003",name:"#chunk 大小设置为 1 Kb"},
{id:"NDN_chunk_zone_size_002",name:"#chunk 大小设置为 1 byte"},
{id:"NDN_chunk_zone_size_001",name:"#Router#chunk 大小设置为 0 byte"},
{id:"NDN_chunk_zone_router_008",name:"#Router#chunk 通过Router 调用get_data 跨Zone 发送端为 zone1_ood 接收端为 zone2_device2 正常流程"},
{id:"NDN_chunk_zone_router_007",name:"#Router#chunk 通过Router 调用get_data 跨Zone 发送端为 zone1_ood 接收端为 zone2_ood 正常流程"},
{id:"NDN_chunk_zone_router_006",name:"#Router#chunk 通过Router 调用get_data 跨Zone 发送端为 zone1_device1 接收端为 zone2_device2 正常流程"},
{id:"NDN_chunk_zone_router_005",name:"#Router#chunk 通过Router 调用get_data 跨Zone 发送端为 zone1_device1 接收端为 zone2_ood 正常流程"},
{id:"NDN_chunk_zone_router_004",name:"#Router#chunk 通过Router 调用get_data 同Zone 发送端为 ood 接收端为 device1 正常流程"},
{id:"NDN_chunk_zone_router_003",name:"#Router#chunk 通过Router 调用get_data 同Zone 发送端为 device1 接收端为 device2 正常流程"},
{id:"NDN_chunk_zone_router_002",name:"#Router#chunk 通过Router 调用get_data 同Zone 发送端为 device1 接收端为 OOD 正常流程"},
{id:"NDN_chunk_zone_router_001",name:"#Router#chunk 通过Router 调用get_data 同Zone 本地传输  正常流程"},
{id:"NDN_chunk_zone_ndn_004",name:"#NDN#chunk 通过NDN 调用get_data 同Zone 发送端为 OOD 接收端为 device1  正常流程"},
{id:"NDN_chunk_zone_ndn_003",name:"#NDN#chunk 通过NDN 调用get_data 同Zone 发送端为 device1 接收端为 device2  正常流程"},
{id:"NDN_chunk_zone_ndn_002",name:"#NDN#chunk 通过NDN 调用get_data 同Zone 发送端为 device1 接收端为OOD  正常流程"},
{id:"NDN_chunk_zone_ndn_001",name:"#NDN#chunk 通过NDN 调用get_data 本地传输 正常流程"},
{id:"NDN_chunk_zone_ndc_001",name:"#NDC#chunk 通过NDC 调用get_data 正常流程"},
]
}