in2 = { action = "in-put", group = { location = "outer" }, access = "accept" }
out2 = { action = "out-put",res = "/*/5aSixgMBVJ1si45iL3REGqZG51pPWA65drBV4rfQkr4L/**" , group = { location = "outer"}, access = "reject" }