import {StackType, testSuiteJson} from '../../common' 
export const datas :testSuiteJson = {
    system: "cyfs-stack",
    module: "NON_put_object",
    testcaseList: [
        { id: "put_object_Param_0021", name: "#put_object handler参数测试 id 设置相同id Chain不同异常场景" },
        { id: "put_object_Param_0020", name: "#put_object handler参数测试 id 设置相同id Chain不同异常场景" },
        { id: "put_object_Param_0019", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseUpdated 类型" },
        { id: "put_object_Param_0018", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseMerged 类型" },
        { id: "put_object_Param_0017", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseAlreadyExists 类型" },
        { id: "put_object_Param_0016", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseAcceptWithSign 类型" },
        { id: "put_object_Param_0015", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponseAccept 类型" },
        { id: "put_object_Param_0014", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerResponse 类型" },
        { id: "put_object_Param_0013", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerPass 类型" },
        { id: "put_object_Param_0012", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerDrop 类型" },
        { id: "put_object_Param_0011", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerReject类型" },
        { id: "put_object_Param_0010", name: "#put_object handler参数测试 routineType 设置为自定义hnadler PutObjectHandlerDefault类型" },
        { id: "put_object_Param_0009", name: "#put_object handler参数测试 index index 数值小的handler生效" },
        { id: "put_object_Param_0008", name: "#put_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Reject" },
        { id: "put_object_Param_0008_01", name: "#put_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Default" },
        { id: "put_object_Param_0007", name: "#put_object handler参数测试 id 设置相同id Default覆盖Reject操作" },
        { id: "put_object_Param_0006", name: "#put_object handler参数测试 id 设置相同id Reject覆盖Default操作" },
        { id: "put_object_Param_0005", name: "#put_object handler参数测试 default_action 设置为Pass" },
        { id: "put_object_Param_0004", name: "#put_object handler参数测试 default_action 设置为Response" },
        { id: "put_object_Param_0003", name: "#put_object handler参数测试 default_action 设置为Drop" },
        { id: "put_object_Param_0002", name: "#put_object handler参数测试 default_action 设置为Reject" },
        { id: "put_object_Param_0001", name: "#put_object handler参数测试 default_action 设置为Default" },
        { id: "put_object_router_0094", name: "#put_object-Router target 为跨zone device2 设置device2 handler PostNOC 为reject" },
        { id: "put_object_router_0093", name: "#put_object-Router target 为跨zone device2 设置device2 handler PreNOC 为reject" },
        { id: "put_object_router_0092", name: "#put_object-Router target 为跨zone device2 设置device2 handler PostRouter 为reject" },
        { id: "put_object_router_0091", name: "#put_object-Router target 为跨zone device2 设置device2 handler PreRouter 为reject" },
        { id: "put_object_router_0090", name: "#put_object-Router target 为跨zone device2 设置device2 ACL in 为reject" },
        { id: "put_object_router_0089", name: "#put_object-Router target 为跨zone device2 设置ood2 ACL OUT 为reject" },
        { id: "put_object_router_0088", name: "#put_object-Router target 为跨zone device2 设置ood2 handler PostForward 为reject" },
        { id: "put_object_router_0087", name: "#put_object-Router target 为跨zone device2 设置ood2 handler PreForward 为reject" },
        { id: "put_object_router_0086", name: "#put_object-Router target 为跨zone device2 设置ood2 handler PostNOC 为reject" },
        { id: "put_object_router_0085", name: "#put_object-Router target 为跨zone device2 设置ood2 handler PreNOC 为reject" },
        { id: "put_object_router_0084", name: "#put_object-Router target 为跨zone device2 设置ood2 handler PostRouter 为reject" },
        { id: "put_object_router_0083", name: "#put_object-Router target 为跨zone device2 设置ood2 handler PreRouter 为reject" },
        { id: "put_object_router_0082", name: "#put_object-Router target 为跨zone device2 设置ood2 ACL-in 为reject" },
        { id: "put_object_router_0081", name: "#put_object-Router target 为跨zone device2 设置ood1 ACL-out 为reject" },
        { id: "put_object_router_0080", name: "#put_object-Router target 为跨zone device2 设置ood1 ACL-in 为reject" },
        { id: "put_object_router_0079", name: "#put_object-Router target 为跨zone device2 设置ood1 PostForward 为reject" },
        { id: "put_object_router_0078", name: "#put_object-Router target 为跨zone device2 设置ood1 PreForward 为reject" },
        { id: "put_object_router_0077", name: "#put_object-Router target 为跨zone device2 设置ood1 PostNOC 为reject" },
        { id: "put_object_router_0076", name: "#put_object-Router target 为跨zone device2 设置ood1 PreNOC 为reject" },
        { id: "put_object_router_0075", name: "#put_object-Router target 为跨zone device2 设置ood1 PostRouter 为reject" },
        { id: "put_object_router_0074", name: "#put_object-Router target 为跨zone device2 设置ood1 PreRouter 为reject" },
        { id: "put_object_router_0073", name: "#put_object-Router target 为跨zone device2 设置device1 ACL-out 为 reject" },
        { id: "put_object_router_0072", name: "#put_object-Router target 为跨zone device2 设置device1 PostForward 为 reject" },
        { id: "put_object_router_0071", name: "#put_object-Router target 为跨zone device2 设置device1 PreForward 为 reject" },
        { id: "put_object_router_0070", name: "#put_object-Router target 为跨zone device2 设置device1 PostNOC为 reject" },
        { id: "put_object_router_0069", name: "#put_object-Router target 为跨zone device2 设置device1 PreNOC为 reject" },
        { id: "put_object_router_0068", name: "#put_object-Router target 为跨zone device2 设置device1 PostRouter为 reject" },
        { id: "put_object_router_0067", name: "#put_object-Router target 为跨zone device2 设置device1 PreRouter为 reject" },
        { id: "put_object_router_0066", name: "#put_object-Router target 为跨zone device2 设置handler-ACL 全部为default" },
        { id: "put_object_router_0065", name: "#put_object-Router target 为跨zone device2 未设置handler-ACL" },
        { id: "put_object_router_0064", name: "#put_object-Router target 为跨zone ood 设置 ood2 handler PostNOC 为reject" },
        { id: "put_object_router_0063", name: "#put_object-Router target 为跨zone ood 设置ood2 handler PreNOC 为reject" },
        { id: "put_object_router_0062", name: "#put_object-Router target 为跨zone ood 设置ood2 handler PostRouter 为reject" },
        { id: "put_object_router_0061", name: "#put_object-Router target 为跨zone ood 设置ood2 handler PreRouter 为reject" },
        { id: "put_object_router_0060", name: "#put_object-Router target 为跨zone ood 设置ood2 ACL-in 为reject" },
        { id: "put_object_router_0059", name: "#put_object-Router target 为跨zone ood 设置ood1 ACL-out 为reject" },
        { id: "put_object_router_0058", name: "#put_object-Router target 为跨zone ood 设置ood1 ACL-in 为reject" },
        { id: "put_object_router_0057", name: "#put_object-Router target 为跨zone ood 设置ood1 PostForward 为reject" },
        { id: "put_object_router_0056", name: "#put_object-Router target 为跨zone ood 设置ood1 PreForward 为reject" },
        { id: "put_object_router_0055", name: "#put_object-Router target 为跨zone ood 设置ood1 PostNOC 为reject" },
        { id: "put_object_router_0054", name: "#put_object-Router target 为跨zone ood 设置ood1 PreNOC 为reject" },
        { id: "put_object_router_0053", name: "#put_object-Router target 为跨zone ood 设置ood1 PostRouter 为reject" },
        { id: "put_object_router_0052", name: "#put_object-Router target 为跨zone ood 设置ood1 PreRouter 为reject" },
        { id: "put_object_router_0051", name: "#put_object-Router target 为跨zone ood 设置device1 ACL-out 为 reject" },
        { id: "put_object_router_0050", name: "#put_object-Router target 为跨zone ood 设置device1 PostForward 为 reject" },
        { id: "put_object_router_0049", name: "#put_object-Router target 为跨zone ood 设置device1 PreForward 为 reject" },
        { id: "put_object_router_0048", name: "#put_object-Router target 为跨zone ood 设置device1 PostNOC为 reject" },
        { id: "put_object_router_0047", name: "#put_object-Router target 为跨zone ood 设置device1 PreNOC为 reject" },
        { id: "put_object_router_0046", name: "#put_object-Router target 为跨zone ood 设置device1 PostRouter为 reject" },
        { id: "put_object_router_0045", name: "#put_object-Router target 为跨zone ood 设置device1 PreRouter为 reject" },
        { id: "put_object_router_0044", name: "#put_object-Router target 为跨zone ood 设置handler-ACL 全部为default" },
        { id: "put_object_router_0043", name: "#put_object-Router target 为跨zone ood 未设置handler-ACL" },
        { id: "put_object_router_0042", name: "#put_object-Router target 为同zone device2 设置device2 handler PostNOC 为reject" },
        { id: "put_object_router_0041", name: "#put_object-Router target 为同zone device2 设置device2 handler PreNOC 为reject" },
        { id: "put_object_router_0040", name: "#put_object-Router target 为同zone device2 设置device2 handler PostRouter 为reject" },
        { id: "put_object_router_0039", name: "#put_object-Router target 为同zone device2 设置device2 handler PreRouter 为reject" },
        { id: "put_object_router_0038", name: "#put_object-Router target 为同zone device2 设置device2 ACL-in 为reject" },
        { id: "put_object_router_0037", name: "#put_object-Router target 为同zone device2 设置ood1 ACL-out 为reject" },
        { id: "put_object_router_0036", name: "#put_object-Router target 为同zone device2 设置ood1 ACL-in 为reject" },
        { id: "put_object_router_0035", name: "#put_object-Router target 为同zone device2 设置ood1 PostForward 为reject" },
        { id: "put_object_router_0034", name: "#put_object-Router target 为同zone device2 设置ood1 PreForward 为reject" },
        { id: "put_object_router_0033", name: "#put_object-Router target 为同zone device2 设置ood1 PostNOC 为reject" },
        { id: "put_object_router_0032", name: "#put_object-Router target 为同zone device2 设置ood1 PreNOC 为reject" },
        { id: "put_object_router_0031", name: "#put_object-Router target 为同zone device2 设置ood1 PostRouter 为reject" },
        { id: "put_object_router_0030", name: "#put_object-Router target 为同zone device2 设置ood1 PreRouter 为reject" },
        { id: "put_object_router_0029", name: "#put_object-Router target 为同zone device2 设置device1 ACL-out 为 reject" },
        { id: "put_object_router_0028_XX", name: "#put_object-Router target 为同zone device2 设置device1 PostForward 为 reject" },
        { id: "put_object_router_0028", name: "#put_object-Router target 为同zone device2 设置device1 PreForward 为 reject" },
        { id: "put_object_router_0027", name: "#put_object-Router target 为同zone device2 设置device1 PostNOC为 reject" },
        { id: "put_object_router_0026", name: "#put_object-Router target 为同zone device2 设置device1 PreNOC为 reject" },
        { id: "put_object_router_0025", name: "#put_object-Router target 为同zone device2 设置device1 PostRouter为 reject" },
        { id: "put_object_router_0024", name: "#put_object-Router target 为同zone device2 设置device1 PreRouter为 reject" },
        { id: "put_object_router_0023", name: "#put_object-Router target 为同zone device2 设置handler-ACL 全部为default" },
        { id: "put_object_router_0022", name: "#put_object-Router target 为同zone device2 未设置handler-ACL" },
        { id: "put_object_router_0021", name: "#put_object-Router target 为同zone OOD  OOD1 设置 PostNOC reject" },
        { id: "put_object_router_0020", name: "#put_object-Router target 为同zone OOD  OOD1 设置 PreNOC reject" },
        { id: "put_object_router_0019", name: "#put_object-Router target 为同zone OOD  OOD1 设置 PostRouter reject" },
        { id: "put_object_router_0018", name: "#put_object-Router target 为同zone OOD  OOD1 设置 PreRouter reject" },
        { id: "put_object_router_0017", name: "#put_object-Router target 为同zone OOD  OOD1 设置 ACL-IN reject" },
        { id: "put_object_router_0016", name: "#put_object-Router target 为同zone OOD  source设备 设置 PostForward reject" },
        { id: "put_object_router_0015", name: "#put_object-Router target 为同zone OOD  source设备 设置 PreForward reject" },
        { id: "put_object_router_0014", name: "#put_object-Router target 为同zone OOD  source设备 设置 PostNOC reject" },
        { id: "put_object_router_0013", name: "#put_object-Router target 为同zone OOD  source设备 设置 PreNOC reject" },
        { id: "put_object_router_0012", name: "#put_object-Router target 为同zone OOD  source设备 设置 PostRouter reject" },
        { id: "put_object_router_0011", name: "#put_object-Router target 为同zone OOD  source设备 设置 PreRouter reject" },
        { id: "put_object_router_0010", name: "#put_object-Router target 为同zone OOD  source设备 设置 OUT ACL reject" },
        { id: "put_object_router_0009", name: "#put_object-Router target 为同zone OOD  设置handler-ACL 为default" },
        { id: "put_object_router_0008", name: "#put_object-Router target 为同zone OOD  未设置handler-ACL" },
        { id: "put_object_router_0007", name: "#put_object-Router target 为本地设备  设置handler PostRouter reject" },
        { id: "put_object_router_0006", name: "#put_object-Router target 为本地设备  设置handler PostRouter reject" },
        { id: "put_object_router_0005", name: "#put_object-Router target 为本地设备  设置handler PostNOC reject" },
        { id: "put_object_router_0004", name: "#put_object-Router target 为本地设备  设置handler PreNOC reject" },
        { id: "put_object_router_0003", name: "#put_object-Router target 为本地设备  设置handler PreRouter reject" },
        { id: "put_object_router_0002", name: "#put_object-Router target 为本地设备  设置handler-ACL为默认" },
        { id: "put_object_router_0001", name: "#put_object-Router target 为本地设备  未设置handler-ACL" },
        { id: "put_object_non_0018", name: "#put_object-NON target 为同zone device2  设置target设备 handler PostNOC reject" },
        { id: "put_object_non_0017", name: "#put_object-NON target 为同zone device2  设置target设备 handler PreNOC reject" },
        { id: "put_object_non_0016", name: "#put_object-NON target 为同zone device2  设置source设备 handler PostForward reject" },
        { id: "put_object_non_0015", name: "#put_object-NON target 为同zone device2  设置source设备 handler PreForward reject" },
        { id: "put_object_non_0014", name: "#put_object-NON target 为同zone device2  设置handler-acl 为默认 default" },
        { id: "put_object_non_0013", name: "#put_object-NON target 为同zone device2  未设置handler-acl 流程 " },
        { id: "put_object_non_0012", name: "#put_object-NON target 为同zone OOD  设置handler OOD PostNOC reject" },
        { id: "put_object_non_0011", name: "#put_object-NON target 为同zone OOD  设置handler OOD PreNOC reject" },
        { id: "put_object_non_0010", name: "#put_object-NON target 为同zone OOD  设置handler OOD ACL reject ACL NON 不生效" },
        { id: "put_object_non_0009", name: "#put_object-NON target 为同zone OOD  设置handler device1 ACL reject，ACL NON 不生效 " },
        { id: "put_object_non_0008", name: "#put_object-NON target 为同zone OOD  设置handler device1 PostForward reject " },
        { id: "put_object_non_0007", name: "#put_object-NON target 为同zone OOD  设置handler device1 PreForward reject " },
        { id: "put_object_non_0006", name: "#put_object-NON target 为同zone OOD  设置handlerACL default-正常流程" },
        { id: "put_object_non_0005", name: "#put_object-NON target 为同zone OOD  无handlerACL流程-正常流程" },
        { id: "put_object_non_0004", name: "#put_object-NON target 本地设备 设置所有handler PostNOC reject" },
        { id: "put_object_non_0003", name: "#put_object-NON target 本地设备 设置所有handler PreNOC reject" },
        { id: "put_object_non_0002", name: "#put_object-NON target 本地设备 设置所有handlerACL default" },
        { id: "put_object_non_0001", name: "#put_object-NON target 本地设备 无handlerACL流程-正常流程" },
        { id: "put_object_noc_0004", name: "#put_object-NOC流程-设置 handler PostNOC reject" },
        { id: "put_object_noc_0003", name: "#put_object-NOC流程-设置 handler PreNOC reject" },
        { id: "put_object_noc_0002", name: "#put_object-NOC流程-设置所有handlerACL default" },
        { id: "put_object_noc_0001", name: "#put_object-NOC 无handlerACL流程-正常流程" },
    ],
    stack_type: StackType.Sim
}