import {testSuiteJson} from '../../common' 
export const datas :testSuiteJson = {
system:"cyfs-stack",
module : "NON_delete_object",
testcaseList : [
{id:"delete_object_Param_0021",name:"#delete_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"delete_object_Param_0020",name:"#delete_object handler参数测试 id 设置相同id Chain不同异常场景"},
{id:"delete_object_Param_0014",name:"#delete_object handler参数测试 routineType 设置为自定义hnadler DeleteObjectHandlerResponse 类型"},
{id:"delete_object_Param_0013",name:"#delete_object handler参数测试 routineType 设置为自定义hnadler DeleteObjectHandlerPass 类型"},
{id:"delete_object_Param_0012",name:"#delete_object handler参数测试 routineType 设置为自定义hnadler DeleteObjectHandlerDrop 类型"},
{id:"delete_object_Param_0011",name:"#delete_object handler参数测试 routineType 设置为自定义hnadler DeleteObjectHandlerReject类型"},
{id:"delete_object_Param_0010",name:"#delete_object handler参数测试 routineType 设置为自定义hnadler DeleteObjectHandlerDefault类型"},
{id:"delete_object_Param_0009",name:"#delete_object handler参数测试 index index 数值小的handler生效"},
{id:"delete_object_Param_0008",name:"#delete_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Reject"},
{id:"delete_object_Param_0008_01",name:"#delete_object handler参数测试 index 设置相同index 先设置的hanlder 生效 Default"},
{id:"delete_object_Param_0007",name:"#delete_object handler参数测试 id 设置相同id Default覆盖Reject操作"},
{id:"delete_object_Param_0006",name:"#delete_object handler参数测试 id 设置相同id Reject覆盖Default操作"},
{id:"delete_object_Param_0005",name:"#delete_object handler参数测试 default_action 设置为Pass"},
{id:"delete_object_Param_0004",name:"#delete_object handler参数测试 default_action 设置为Response"},
{id:"delete_object_Param_0003",name:"#delete_object handler参数测试 default_action 设置为Drop"},
{id:"delete_object_Param_0002",name:"#delete_object handler参数测试 default_action 设置为Reject"},
{id:"delete_object_Param_0001",name:"#delete_object handler参数测试 default_action 设置为Default"},
{id:"delete_object_router_0070",name:"#delete_object-Router target 为跨zone device2 设置device2 handler PostNOC 为reject"},
{id:"delete_object_router_0069",name:"#delete_object-Router target 为跨zone device2 设置device2 handler PreNOC 为reject"},
{id:"delete_object_router_0068",name:"#delete_object-Router target 为跨zone device2 设置device2 handler PostRouter 为reject"},
{id:"delete_object_router_0067",name:"#delete_object-Router target 为跨zone device2 设置device2 handler PreRouter 为reject"},
{id:"delete_object_router_0066",name:"#delete_object-Router target 为跨zone device2 设置device2 ACL in 为reject"},
{id:"delete_object_router_0065",name:"#delete_object-Router target 为跨zone device2 设置device1 ACL-out 为 reject"},
{id:"delete_object_router_0064",name:"#delete_object-Router target 为跨zone device2 设置device1 PostForward 为 reject"},
{id:"delete_object_router_0063",name:"#delete_object-Router target 为跨zone device2 设置device1 PreForward 为 reject"},
{id:"delete_object_router_0062",name:"#delete_object-Router target 为跨zone device2 设置device1 PostNOC为 reject"},
{id:"delete_object_router_0061",name:"#delete_object-Router target 为跨zone device2 设置device1 PreNOC为 reject"},
{id:"delete_object_router_0060",name:"#delete_object-Router target 为跨zone device2 设置device1 PostRouter为 reject"},
{id:"delete_object_router_0059",name:"#delete_object-Router target 为跨zone device2 设置device1 PreRouter为 reject"},
{id:"delete_object_router_0058",name:"#delete_object-Router target 为跨zone device2 设置handler-ACL 全部为default"},
{id:"delete_object_router_0057",name:"#delete_object-Router target 为跨zone device2 未设置handler-ACL"},
{id:"delete_object_router_0056",name:"#delete_object-Router target 为跨zone ood 设置 ood2 handler PostNOC 为reject"},
{id:"delete_object_router_0055",name:"#delete_object-Router target 为跨zone ood 设置ood2 handler PreNOC 为reject"},
{id:"delete_object_router_0054",name:"#delete_object-Router target 为跨zone ood 设置ood2 handler PostRouter 为reject"},
{id:"delete_object_router_0053",name:"#delete_object-Router target 为跨zone ood 设置ood2 handler PreRouter 为reject"},
{id:"delete_object_router_0052",name:"#delete_object-Router target 为跨zone ood 设置ood2 ACL-in 为reject"},
{id:"delete_object_router_0051",name:"#delete_object-Router target 为跨zone ood 设置device1 ACL-out 为 reject"},
{id:"delete_object_router_0050",name:"#delete_object-Router target 为跨zone ood 设置device1 PostForward 为 reject"},
{id:"delete_object_router_0049",name:"#delete_object-Router target 为跨zone ood 设置device1 PreForward 为 reject"},
{id:"delete_object_router_0048",name:"#delete_object-Router target 为跨zone ood 设置device1 PostNOC为 reject"},
{id:"delete_object_router_0047",name:"#delete_object-Router target 为跨zone ood 设置device1 PreNOC为 reject"},
{id:"delete_object_router_0046",name:"#delete_object-Router target 为跨zone ood 设置device1 PostRouter为 reject"},
{id:"delete_object_router_0045",name:"#delete_object-Router target 为跨zone ood 设置device1 PreRouter为 reject"},
{id:"delete_object_router_0044",name:"#delete_object-Router target 为跨zone ood 设置handler-ACL 全部为default"},
{id:"delete_object_router_0043",name:"#delete_object-Router target 为跨zone ood 未设置handler-ACL"},
{id:"delete_object_router_0042",name:"#delete_object-Router target 为同zone device2 设置device2 handler PostNOC 为reject"},
{id:"delete_object_router_0041",name:"#delete_object-Router target 为同zone device2 设置device2 handler PreNOC 为reject"},
{id:"delete_object_router_0040",name:"#delete_object-Router target 为同zone device2 设置device2 handler PostRouter 为reject"},
{id:"delete_object_router_0039",name:"#delete_object-Router target 为同zone device2 设置device2 handler PreRouter 为reject"},
{id:"delete_object_router_0038",name:"#delete_object-Router target 为同zone device2 设置device2 ACL-in 为reject"},
{id:"delete_object_router_0029",name:"#delete_object-Router target 为同zone device2 设置device1 ACL-out 为 reject"},
{id:"delete_object_router_0028",name:"#delete_object-Router target 为同zone device2 设置device1 PostForward 为 reject"},
{id:"delete_object_router_0028_A",name:"#delete_object-Router target 为同zone device2 设置device1 PreForward 为 reject"},
{id:"delete_object_router_0027",name:"#delete_object-Router target 为同zone device2 设置device1 PostNOC为 reject"},
{id:"delete_object_router_0026",name:"#delete_object-Router target 为同zone device2 设置device1 PreNOC为 reject"},
{id:"delete_object_router_0025",name:"#delete_object-Router target 为同zone device2 设置device1 PostRouter为 reject"},
{id:"delete_object_router_0024",name:"#delete_object-Router target 为同zone device2 设置device1 PreRouter为 reject"},
{id:"delete_object_router_0023",name:"#delete_object-Router target 为同zone device2 设置handler-ACL 全部为default"},
{id:"delete_object_router_0022",name:"#delete_object-Router target 为同zone device2 未设置handler-ACL"},
{id:"delete_object_router_0021",name:"#delete_object-Router target 为同zone OOD  OOD1 设置 PostNOC reject"},
{id:"delete_object_router_0020",name:"#delete_object-Router target 为同zone OOD  OOD1 设置 PreNOC reject"},
{id:"delete_object_router_0019",name:"#delete_object-Router target 为同zone OOD  OOD1 设置 PostRouter reject"},
{id:"delete_object_router_0018",name:"#delete_object-Router target 为同zone OOD  OOD1 设置 PreRouter reject"},
{id:"delete_object_router_0017",name:"#delete_object-Router target 为同zone OOD  OOD1 设置 ACL-IN reject"},
{id:"delete_object_router_0016",name:"#delete_object-Router target 为同zone OOD  source设备 设置 PostForward reject"},
{id:"delete_object_router_0015",name:"#delete_object-Router target 为同zone OOD  source设备 设置 PreForward reject"},
{id:"delete_object_router_0014",name:"#delete_object-Router target 为同zone OOD  source设备 设置 PostNOC reject"},
{id:"delete_object_router_0013",name:"#delete_object-Router target 为同zone OOD  source设备 设置 PreNOC reject"},
{id:"delete_object_router_0012",name:"#delete_object-Router target 为同zone OOD  source设备 设置 PostRouter reject"},
{id:"delete_object_router_0011",name:"#delete_object-Router target 为同zone OOD  source设备 设置 PreRouter reject"},
{id:"delete_object_router_0010",name:"#delete_object-Router target 为同zone OOD  source设备 设置 OUT ACL reject"},
{id:"delete_object_router_0009",name:"#delete_object-Router target 为同zone OOD  设置handler-ACL 为default"},
{id:"delete_object_router_0008",name:"#delete_object-Router target 为同zone OOD  未设置handler-ACL"},
{id:"delete_object_router_0007",name:"#delete_object-Router target 为本地设备  设置handler PostRouter reject"},
{id:"delete_object_router_0006",name:"#delete_object-Router target 为本地设备  设置handler PostRouter reject"},
{id:"delete_object_router_0005",name:"#delete_object-Router target 为本地设备  设置handler PostNOC reject"},
{id:"delete_object_router_0004",name:"#delete_object-Router target 为本地设备  设置handler PreNOC reject"},
{id:"delete_object_router_0003",name:"#delete_object-Router target 为本地设备  设置handler PreRouter reject"},
{id:"delete_object_router_0002",name:"#delete_object-Router target 为本地设备  设置handler-ACL为默认"},
{id:"delete_object_router_0001",name:"#delete_object-Router target 为本地设备  未设置handler-ACL"},
{id:"delete_object_non_0017",name:"#delete_object-NON target 为同zone device2  设置target设备 handler PostNOC reject"},
{id:"delete_object_non_0016",name:"#delete_object-NON target 为同zone device2  设置target设备 handler PreNOC reject"},
{id:"delete_object_non_0015_2",name:"#delete_object-NON target 为同zone device2  设置source设备 handler PostForward reject"},
{id:"delete_object_non_0015",name:"#delete_object-NON target 为同zone device2  设置source设备 handler PreForward reject"},
{id:"delete_object_non_0014",name:"#delete_object-NON target 为同zone device2  设置handler-acl 为默认 default"},
{id:"delete_object_non_0013",name:"#delete_object-NON target 为同zone device2  未设置handler-acl 流程 "},
{id:"delete_object_non_0012",name:"#delete_object-NON target 为同zone OOD  设置handler OOD PostNOC reject"},
{id:"delete_object_non_0011",name:"#delete_object-NON target 为同zone OOD  设置handler OOD PreNOC reject"},
{id:"delete_object_non_0010",name:"#delete_object-NON target 为同zone OOD  设置handler OOD ACL reject "},
{id:"delete_object_non_0009",name:"#delete_object-NON target 为同zone OOD  设置handler device1 ACL reject "},
{id:"delete_object_non_0008",name:"#delete_object-NON target 为同zone OOD  设置handler device1 PostForward reject "},
{id:"delete_object_non_0007",name:"#delete_object-NON target 为同zone OOD  设置handler device1 PreForward reject "},
{id:"delete_object_non_0006",name:"#delete_object-NON target 为同zone OOD  设置handlerACL default-正常流程"},
{id:"delete_object_non_0005",name:"#delete_object-NON target 为同zone OOD  无handlerACL流程-正常流程"},
{id:"delete_object_non_0004",name:"#delete_object-NON target 本地设备 设置所有handler PostNOC reject"},
{id:"delete_object_non_0003",name:"#delete_object-NON target 本地设备 设置所有handler PreNOC reject"},
{id:"delete_object_non_0002",name:"#delete_object-NON target 本地设备 设置所有handlerACL default"},
{id:"delete_object_non_0001",name:"#delete_object-NON target 本地设备 无handlerACL流程-正常流程"},
{id:"delete_object_noc_0004",name:"#delete_object-NOC流程-设置 handler PostNOC reject"},
{id:"delete_object_noc_0003",name:"#delete_object-NOC流程-设置 handler PreNOC reject"},
{id:"delete_object_noc_0002",name:"#delete_object-NOC流程-设置所有handlerACL default"},
{id:"delete_object_noc_0001",name:"#delete_object-NOC 无handlerACL流程-正常流程"},
]
}