[workspace]
resolver = "2"

members=[
    "bdt-tools",
    "cyfs-tools",
    "cyfs-stack-test-rust",
    "test-simulator"
]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false
