in2 = { action = "in-put",res = "/9tGpLNnGfMgXZ2xqmVmqFhh91PQXLkaXbccyw2nkdDMM/**", group = { location = "outer" }, access = "accept" }
out2 = { action = "out-put", group = { location = "outer"}, access = "accept" }